name: Format PR Files

on:
  pull_request:
    paths:
      - '**/*.md'  # 仅当 PR 中修改了 .md 文件时触发工作流

jobs:
  whitespace:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git config
        run: |
        git config --global user.name "miyaliu"
        git config --global user.email "miyaliu66666@gmail.com"

      - name: Remove trailing whitespaces from Markdown files
        run: |
          echo "Target branch: ${{ github.event.pull_request.base.ref }}"
          echo "Head branch: ${{ github.event.pull_request.head.ref }}"
          
          # 获取目标分支（main）与源分支（HEAD）之间的基准提交
          base_branch="${{ github.event.pull_request.base.ref }}"
          head_branch="${{ github.event.pull_request.head.ref }}"
          
          git fetch origin $base_branch
          git fetch origin $head_branch
          
          base_commit=$(git merge-base origin/$base_branch origin/$head_branch)
          echo "Base commit: $base_commit"
          
          # 获取当前 PR 中的修改文件
          echo "Checking changes in PR..."
          files=$(git diff --name-only $base_commit origin/$head_branch)
          echo "Changed files: $files"

          # 过滤出 .md 文件
          file=$(echo "$files" | grep '\.md$')
          echo "Filtered .md file: $file"

          if [ -n "$file" ]; then
            echo "Processing file: $file"
            # 删除文件中每一行的末尾空格
            sed -i 's/ $//g' "$file"
            git add "$file"
            git commit -m "Remove trailing spaces from $file"
            git push origin HEAD  # 推送更改到当前 PR 分支
          else
            echo "No .md files found or no changes to commit."
          fi