name: Format PR Files

on:
  pull_request:
    paths:
      - '**/*.md'

jobs:
  whitespace:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch latest changes
        run: git fetch origin

      - name: Remove trailing whitespaces from Markdown files
        run: |
          file=$(git diff --name-only HEAD | grep '\.md$')
          if [ -n "$file" ]; then
            sed -i 's/ $//g' "$file"
            git add "$file"
            git commit -m "Remove trailing spaces from $file"
            git push origin HEAD
          fi