name: Format PR Files

on:
  pull_request:
    paths:
      - '**/*.md'  # 仅当 PR 中修改了 .md 文件时触发工作流

jobs:
  whitespace:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Remove trailing whitespaces from Markdown files
        run: |
          # 获取当前 PR 中的修改文件
          echo "Checking changes in PR..."
          files=$(git diff --name-only HEAD^ HEAD)
          echo "Changed files: $files"

          # 过滤出 .md 文件
          file=$(echo "$files" | grep '\.md$')
          echo "Filtered .md file: $file"

          if [ -n "$file" ]; then
            echo "Processing file: $file"
            # 删除文件中每一行的末尾空格
            sed -i 's/ $//g' "$file"
            git add "$file"
            git commit -m "Remove trailing spaces from $file"
            git push origin HEAD  # 推送更改到当前 PR 分支
          else
            echo "No .md files found or no changes to commit."
          fi